before_script:
  - whoami
  - sudo docker --version

stages:
  - build
  - deploy_staging
  - deploy

build:
  tags: 
    - production1
    - jupyter-STA663
  stage: build
  script: 
    - echo "Building the app in staging"
    - cd src/STA663-notebook; pwd; ls -la
    - ./build-test


deploy_staging:
  tags: 
    - production1
    - jupyter-STA663
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - cd docker-scripts; pwd; ls -la; ./run-test-instance
  environment:
    name: staging
  only:
  - staging


deploy_production:
  tags: 
    - production1
    - jupyter-STA663
  stage: deploy
  script:
    - echo "Building the production app"
    - cd src/STA663-notebook; pwd; ls -la
    - ./build-production
    - echo "Deploy to production server"
    - cd /srv/persistent-data/docker-scripts; ./run-everything
  environment:
    name: production
  when: manual
  only:
  - master

